projects:
  - match: Test.*
    labels:
      - required: ["good first issue"]
        whitelist: ["bug"]
        blacklist: ["enhancement"]
      - required: ["help wanted"]
        whitelist: ["enhancement"]
  - match: Docs
    labels:
      - required: ["documentation"]
