name: "Project labeler"
description: "Github Action for adding labels to issues based on project"
author: "Dmitry Bondarenko"
inputs:
  repo-token:
    description: "The GITHUB_TOKEN secret"
  configuration-path:
    description: "The path for the label configurations of projects"
    default: ".github/project-labeler.yml"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  color: gray-dark
  icon: flag
