name: "Project labeler"
description: "Github Action for adding labels to issues based on project"
author: "Dmitry Bondarenko"
inputs:
  repo-token:
    description: "The GITHUB_TOKEN secret"
runs:
  using: "node12"
  main: "dist/index.js"
