name: "build-test"
on: # rebuild any PRs and main branch changes
  issues:
    types:
      - assigned

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
